### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by DanielGurianov** [Revadike/SteamKey.Trade#4]
Pretty self explanatory, let users get notified when X happens.
X:
New incoming trades,
New Accepted offers,
New Bundle (Are we doing bundles like barter or naw?),
New comment –
From user trading with
From another community member
---all with options to enable / disable.

**Comment by Revadike** [comment]
Dupe of https://github.com/Revadike/SteamKey.Trade/issues/51

**Comment by Revadike** [comment]
Duplicate of #51
