### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by DanielGurianov** [Revadike/SteamKey.Trade#5]
Make Sync work-
Syncing owned apps/packages,
Preferably much better than barters, with demo syncing and correct package syncing.

If possible make an even better sync- 
Packages that are not owned directly but have all the contents inside them already owned from other packages also show as owned.

Ofc, also syncing wishlist

**Comment by Revadike** [comment]
Duplicate of #68 
Duplicate of #57

**Comment by Revadike** [comment]
Duplicate of #68 #57

**Comment by Revadike** [comment]
Duplicate of #57
