### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by kissofkill** [Revadike/SteamKey.Trade#53]
first thing you'll see (as a new user) is a text field to import your tradables, or pick the option to import from steamtrades, reddit or barter.vg

**Comment by Revadike** [comment]
Maybe also show some feeds or a [H] and [W] search function?

**Comment by KLiKzg** [comment]
Not only import from Barter, as lots of us will transfer our trades to next best thing (until this trading page is made) to LesTrades. So can we have import from Barter & LesTrades, but not only game data list, but also bundle list. As some of us have used a lot of time to arrange all TL games to bundles.

**Comment by Revadike** [comment]
> Not only import from Barter, as lots of us will transfer our trades to next best thing (until this trading page is made) to LesTrades. So can we have import from Barter & LesTrades, but not only game data list, but also bundle list. As some of us have used a lot of time to arrange all TL games to bundles.

TL games? Also, import what bundle list? As far as I know we don't have personal bundle lists on barter?
As for importing from lestrades, could you make a new issue for it @KLiKzg ?

**Comment by Revadike** [comment]
Mockup by @DanielGurianov 
![Image](https://github.com/user-attachments/assets/bbd250f7-708c-4e32-96c6-919df8f10c62)

**Comment by Revadike** [comment]
Good enough for now
![Image](https://github.com/user-attachments/assets/a837a15e-6f92-493b-9876-af13df7eb364)
