### ISSUE TITLE
Dynamic Label-Rich Rating System

### ISSUE THREAD

**Issue by kissofkill** [Revadike/SteamKey.Trade#55]
rating system like steamtrades, but with labels you can select: quick, professional, kind, generous, helpful, slow, rude, lowballer, scammer, unprofessional. Show a counter of each label on profiles.

**Comment by Revadike** [comment]
As discussed in discord, we decided to go with a different direction
![image](https://github.com/user-attachments/assets/75635ac4-50fd-4a7b-ae14-4c4e67e253c5)
