### ISSUE TITLE
Web page for sending & receiving offers

### ISSUE THREAD

**Issue by KLiKzg** [Revadike/SteamKey.Trade#97]
A limited options web page to work with your server & app, in order to make trades also through web site. 

Limited options are only for Steam/GOG (etc.) sync, Have List, Trade List, Want List, Matching & Offers. Like we have on Barter!

App is still a way to go, for "safe trading option" & other extra features.

**Comment by Revadike** [comment]
Not sure what you mean?
We already have the ability to send trade offers.

**Comment by KLiKzg** [comment]
For the ones who would opt out, not to use the app...to have a limited version of web page, with link to central server for trading. Is that possible?

**Comment by Revadike** [comment]
what app? there is only one website

**Comment by KLiKzg** [comment]
OK, then looking forward for you to upload & start testing this webpage. 👍

**Comment by Revadike** [comment]
> OK, then looking forward for you to upload & start testing this webpage. 👍

Thank you, me too.
